//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTest3
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Computes
        {
            
            /// <summary> Asset Path (Computes/AtmosphereCompute.wefx) </summary>
            public static readonly Guid AtmosphereCompute = new Guid("df2ab68e-2005-4a33-af58-1f9bcf68fe27");
            
            /// <summary> Asset Path (Computes/BilateralBlur.wefx) </summary>
            public static readonly Guid BilateralBlur = new Guid("7af338ce-d619-4ea9-90d3-a37638c00f77");
            
            /// <summary> Asset Path (Computes/Blend.wefx) </summary>
            public static readonly Guid Blend = new Guid("eaa0fbbb-3923-4a8d-9a4b-c5ac569a30c1");
            
            /// <summary> Asset Path (Computes/Bloom.wefx) </summary>
            public static readonly Guid Bloom = new Guid("f2bd0fb3-fe4a-4589-88a2-c6f985fa434f");
            
            /// <summary> Asset Path (Computes/BloomThreshold.wefx) </summary>
            public static readonly Guid BloomThreshold = new Guid("5c805d88-78de-4f25-b2b8-40c45a54a344");
            
            /// <summary> Asset Path (Computes/BokehBlur.wefx) </summary>
            public static readonly Guid BokehBlur = new Guid("0aea5c88-be16-4260-99c3-f92746d9ca72");
            
            /// <summary> Asset Path (Computes/BokehCoCDownscale.wefx) </summary>
            public static readonly Guid BokehCoCDownscale = new Guid("4e1cc8ff-0b41-4964-a558-efcf4200f143");
            
            /// <summary> Asset Path (Computes/BokehCombine.wefx) </summary>
            public static readonly Guid BokehCombine = new Guid("6990cd81-4fde-40c8-a4bf-4ef8871dac2f");
            
            /// <summary> Asset Path (Computes/BokehExtractFields.wefx) </summary>
            public static readonly Guid BokehExtractFields = new Guid("d745fa1a-13d0-4547-8e68-ac04f491581e");
            
            /// <summary> Asset Path (Computes/BokehNearBorder.wefx) </summary>
            public static readonly Guid BokehNearBorder = new Guid("9c96630f-c22f-44dc-b347-ad11aaea95ef");
            
            /// <summary> Asset Path (Computes/BokehNearHalo.wefx) </summary>
            public static readonly Guid BokehNearHalo = new Guid("7ab68877-e067-4eda-8293-8179d020102d");
            
            /// <summary> Asset Path (Computes/CameraMotionBlur.wefx) </summary>
            public static readonly Guid CameraMotionBlur = new Guid("f5e59513-0d6f-4051-9331-586ccd951ef3");
            
            /// <summary> Asset Path (Computes/DownSample.wefx) </summary>
            public static readonly Guid DownSample = new Guid("8681008a-73c9-4337-96da-e081b4dff24d");
            
            /// <summary> Asset Path (Computes/Enabled.wefx) </summary>
            public static readonly Guid Enabled = new Guid("3fc3ec67-408d-4795-a1b5-5e198fbc24af");
            
            /// <summary> Asset Path (Computes/Fog.wefx) </summary>
            public static readonly Guid Fog = new Guid("37886c87-58a8-408e-a53c-d851fde2f383");
            
            /// <summary> Asset Path (Computes/FXAA.wefx) </summary>
            public static readonly Guid FXAA = new Guid("d5577c1c-52e0-4071-a1bd-928339880bc3");
            
            /// <summary> Asset Path (Computes/Gaussian.wefx) </summary>
            public static readonly Guid Gaussian = new Guid("b1053619-59d0-4ea4-ba62-b7c85716c117");
            
            /// <summary> Asset Path (Computes/Histogram.wefx) </summary>
            public static readonly Guid Histogram = new Guid("d743adde-eb54-4f0b-8bc3-e431a34f762d");
            
            /// <summary> Asset Path (Computes/IrradianceCompute.wefx) </summary>
            public static readonly Guid IrradianceCompute = new Guid("0a86c4bc-1891-4776-8971-04f894169bc1");
            
            /// <summary> Asset Path (Computes/IsolatingSky.wefx) </summary>
            public static readonly Guid IsolatingSky = new Guid("83489f84-2293-4dd6-bce0-5a479f533fc9");
            
            /// <summary> Asset Path (Computes/LensFlare.wefx) </summary>
            public static readonly Guid LensFlare = new Guid("120f7347-14bc-423c-8d37-65ee4e32e0dd");
            
            /// <summary> Asset Path (Computes/LightShaft.wefx) </summary>
            public static readonly Guid LightShaft = new Guid("347a536f-f394-4ea7-b32c-0ff81598eedd");
            
            /// <summary> Asset Path (Computes/LuminanceAvg.wefx) </summary>
            public static readonly Guid LuminanceAvg = new Guid("d7cba48c-3058-4386-9a0a-27bf8925bfaf");
            
            /// <summary> Asset Path (Computes/Mediam.wefx) </summary>
            public static readonly Guid Mediam = new Guid("fc650ac8-a6df-4f36-b9fc-55759cd5d811");
            
            /// <summary> Asset Path (Computes/RadianceCompute.wefx) </summary>
            public static readonly Guid RadianceCompute = new Guid("d0cd29fb-701e-4e2e-b6af-d9d138675e06");
            
            /// <summary> Asset Path (Computes/ReconstructFromDepth.wefx) </summary>
            public static readonly Guid ReconstructFromDepth = new Guid("ed92c3b2-44a0-4592-8d8e-e48ca4de92e4");
            
            /// <summary> Asset Path (Computes/Sharpen.wefx) </summary>
            public static readonly Guid Sharpen = new Guid("5df13f05-a063-420e-a506-59ed04203d70");
            
            /// <summary> Asset Path (Computes/SkinningCompute.wefx) </summary>
            public static readonly Guid SkinningCompute = new Guid("c5af55c9-063d-49c7-bb65-aa31062251a2");
            
            /// <summary> Asset Path (Computes/SSAO.wefx) </summary>
            public static readonly Guid SSAO = new Guid("5c884db4-9e59-4a00-8e17-62487eef9937");
            
            /// <summary> Asset Path (Computes/SSR.wefx) </summary>
            public static readonly Guid SSR = new Guid("e6a559e1-c8f7-4729-b36d-85a2ecb63ad5");
            
            /// <summary> Asset Path (Computes/SSRResolve.wefx) </summary>
            public static readonly Guid SSRResolve = new Guid("71506dd4-43b7-4e35-8d0c-a16cc7237083");
            
            /// <summary> Asset Path (Computes/TAA.wefx) </summary>
            public static readonly Guid TAA = new Guid("b4fdb094-d620-4252-b523-aa5182745b32");
            
            /// <summary> Asset Path (Computes/ToneMapping.wefx) </summary>
            public static readonly Guid ToneMapping = new Guid("c0529ee7-8b51-45f2-aa39-8167614dc8af");
        }
        
        public sealed class Effects
        {
            
            /// <summary> Asset Path (Effects/AtmosphericEffect.wefx) </summary>
            public static readonly Guid AtmosphericEffect = new Guid("d551eb2b-202d-454d-a059-c3ddce284636");
            
            /// <summary> Asset Path (Effects/AtmosphericQuadEffect.wefx) </summary>
            public static readonly Guid AtmosphericQuadEffect = new Guid("d68b16ac-1b98-4b1a-95f6-eb39a41b70ec");
            
            /// <summary> Asset Path (Effects/BillboardEffect.wefx) </summary>
            public static readonly Guid BillboardEffect = new Guid("dbb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/DistortionEffect.wefx) </summary>
            public static readonly Guid DistortionEffect = new Guid("d672019c-2887-4056-a0e7-2141d2fe5f78");
            
            /// <summary> Asset Path (Effects/LineBatchEffect.wefx) </summary>
            public static readonly Guid LineBatchEffect = new Guid("dcb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/LineEffect.wefx) </summary>
            public static readonly Guid LineEffect = new Guid("ddb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/MyEffect.wefx) </summary>
            public static readonly Guid MyEffect = new Guid("ff3f26aa-14d2-4dca-942b-b39b4cfc9eab");
            
            /// <summary> Asset Path (Effects/RenderQuad.wefx) </summary>
            public static readonly Guid RenderQuad = new Guid("dfb5efbf-33e9-4b56-836d-cb8ca4ca0c80");
            
            /// <summary> Asset Path (Effects/SkyboxEffect.wefx) </summary>
            public static readonly Guid SkyboxEffect = new Guid("dd86a555-371c-4c72-8cf3-c32d5219af74");
            
            /// <summary> Asset Path (Effects/SpriteBatchEffect.wefx) </summary>
            public static readonly Guid SpriteBatchEffect = new Guid("deb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/StandardEffect.wefx) </summary>
            public static readonly Guid StandardEffect = new Guid("daa1f60a-82ad-40fc-8fbb-7b85caa6de0a");
        }
        
        public sealed class Materials
        {
            
            /// <summary> Asset Path (Materials/DefaultMaterial.wemt) </summary>
            public static readonly Guid DefaultMaterial = new Guid("02181b63-5a0e-46d1-9208-d92376ae33fb");
            
            /// <summary> Asset Path (Materials/DistortionMat.wemt) </summary>
            public static readonly Guid DistortionMat = new Guid("5f795365-07f5-4b56-83df-043eb40a7457");
            
            /// <summary> Asset Path (Materials/MyMaterial.wemt) </summary>
            public static readonly Guid MyMaterial = new Guid("324e7a12-f162-40ba-8239-2a3b0a252aa4");
        }
        
        public sealed class Models
        {
        }
        
        public sealed class PostProcessingGraphs
        {
            
            /// <summary> Asset Path (PostProcessingGraphs/DefaultPostProcessingGraph.wepp) </summary>
            public static readonly Guid DefaultPostProcessingGraph = new Guid("dd593717-0922-4f58-9c85-c309658eff03");
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary> Asset Path (RenderLayers/Alpha.werl) </summary>
            public static readonly Guid Alpha = new Guid("e35c59a9-26ab-4b4c-8210-4b1f21c31530");
            
            /// <summary> Asset Path (RenderLayers/Opaque.werl) </summary>
            public static readonly Guid Opaque = new Guid("0db59561-b3f5-444f-b5de-e62e3a5b42bf");
            
            /// <summary> Asset Path (RenderLayers/Skybox.werl) </summary>
            public static readonly Guid Skybox = new Guid("da9e0221-f777-4e5a-96c2-df012f2d7bf2");
        }
        
        public sealed class Samplers
        {
            
            /// <summary> Asset Path (Samplers/LinearClampSampler.wesp) </summary>
            public static readonly Guid LinearClampSampler = new Guid("7d1e2792-2031-42bb-a67c-0dbd282be12a");
            
            /// <summary> Asset Path (Samplers/LinearWrapSampler.wesp) </summary>
            public static readonly Guid LinearWrapSampler = new Guid("9018edf8-ea96-4721-bf83-5561942432e0");
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Asset Path (Scenes/MyScene.wescene.wesc) </summary>
            public static readonly Guid MyScene_wescene = new Guid("4da00136-65c1-4805-9a89-37df2733a46c");
        }
        
        public sealed class Textures
        {
            
            /// <summary> Asset Path (Textures/BlueNoise.png.wetx) </summary>
            public static readonly Guid BlueNoise_png = new Guid("85459c5f-78da-4ed0-9038-26d2dd27280d");
            
            /// <summary> Asset Path (Textures/Checker.png.wetx) </summary>
            public static readonly Guid Checker_png = new Guid("8b1d459c-c433-4ee3-bfe5-b45fbce12736");
            
            /// <summary> Asset Path (Textures/dfgLut.png.wetx) </summary>
            public static readonly Guid dfgLut_png = new Guid("d81d459c-c433-4ee3-bfe5-b45fbce12736");
            
            /// <summary> Asset Path (Textures/DistortionTexture.png.wetx) </summary>
            public static readonly Guid DistortionTexture_png = new Guid("34b16253-37ce-457a-bd5b-3ed27bb51738");
            
            /// <summary> Asset Path (Textures/FlareGradient.png.wetx) </summary>
            public static readonly Guid FlareGradient_png = new Guid("1104127f-8a0e-4a1c-9b8c-b8832362a809");
            
            /// <summary> Asset Path (Textures/FlareStarburst.png.wetx) </summary>
            public static readonly Guid FlareStarburst_png = new Guid("385d88a2-9a0c-4275-ac7d-499207f1bae0");
            
            /// <summary> Asset Path (Textures/LensDirt00.png.wetx) </summary>
            public static readonly Guid LensDirt00_png = new Guid("75a8073c-1878-4160-a92d-da0d7530cbb6");
        }
    }
}
